### ISSUE TITLE
挺好用的，有几个问题请教一下。

### ISSUE THREAD

**Issue by rillzhang** [ysbing/yadb#1]
还是挺好用的，感谢。有几个问题哈：
1. uc浏览器里无法输入网址，不知道什么情况？
2. 想了解一下这个app_process这个命令的一些具体功能，资料偏少。跟adb shell am instrument这种调起android测试类的方式有什么区别？
3. 是否可以实现获取手机应用的布局文件的功能？

**Comment by ysbing** [comment]
> 还是挺好用的，感谢。有几个问题哈：
> 
> 1. uc浏览器里无法输入网址，不知道什么情况？
> 2. 想了解一下这个app_process这个命令的一些具体功能，资料偏少。跟adb shell am instrument这种调起android测试类的方式有什么区别？
> 3. 是否可以实现获取手机应用的布局文件的功能？

1.uc浏览器的我测了是不行，但可以修，修后我再跟你说
2.这个命令的权限很高，执行后拥有相当高的权限，可以干很多事情，资料的话，你看下scrcpy这个库还有Google上的资料
3.adb shell uiautomator dump --compressed，我使用这个来获取手机布局，但有些界面获取失败，但大部分是可以的

**Comment by rillzhang** [comment]
> > 还是挺好用的，感谢。有几个问题哈：
> > 
> > 1. uc浏览器里无法输入网址，不知道什么情况？
> > 2. 想了解一下这个app_process这个命令的一些具体功能，资料偏少。跟adb shell am instrument这种调起android测试类的方式有什么区别？
> > 3. 是否可以实现获取手机应用的布局文件的功能？
> 
> 1.uc浏览器的我测了是不行，但可以修，修后我再跟你说
> 2.这个命令的权限很高，执行后拥有相当高的权限，可以干很多事情，资料的话，你看下scrcpy这个库还有Google上的资料
> 3.adb shell uiautomator dump --compressed，我使用这个来获取手机布局，但有些界面获取失败，但大部分是可以的
好的，谢谢哈。
adb shell uiautomator dump 这种方式取不到视频、秒表等动态的界面布局。am instrument调用androidTest的AccessibilityServiceInfo无障碍服务倒是可以。不知道yadb这种方式能调用android的api么？

**Comment by ysbing** [comment]
已支持获取布局
