### ISSUE TITLE
yadb好像不支持三星设备，有什么别的处理方式吗？

### ISSUE THREAD

**Issue by TimRChen** [ysbing/yadb#11]

**Comment by ysbing** [comment]
> _No description provided._

错误截图发出来

**Comment by wen-xi-da** [comment]
> > _No description provided._
> 
> 错误截图发出来
![image](https://github.com/ysbing/yadb/assets/49971400/cfe27c36-8209-4402-98b4-5e7e0bc7a8be)

**Comment by wen-xi-da** [comment]
> > _No description provided._
> 
> 错误截图发出来

![image](https://github.com/ysbing/yadb/assets/49971400/d6834fd9-34ab-4844-9056-92f8ad297dca)

**Comment by ysbing** [comment]
> > > _No description provided._
> > 
> > 
> > 错误截图发出来
> 
> ![image](https://private-user-images.githubusercontent.com/49971400/292429890-d6834fd9-34ab-4844-9056-92f8ad297dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM5MjgsIm5iZiI6MTcwMzQ5MzYyOCwicGF0aCI6Ii80OTk3MTQwMC8yOTI0Mjk4OTAtZDY4MzRmZDktMzRhYi00ODQ0LTkwNTYtOTJmOGFkMjk3ZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4NDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjcxNDAzYzAwM2I5MWMxOGJmMWYwNWQ1NzZmODFjYjM2NmY4Y2I2ZTE2MTJiNjc3MDg3NjM4N2JjMmUwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DmGb45kM5Vwdf_DjZKHES5BHelyVEWxsNpLNIda7Dfc)

已修复，可以用最新的yadb
