### ISSUE TITLE
为什么中文输入后还是乱码呢？

### ISSUE THREAD

**Issue by zhucan3n** [ysbing/yadb#15]
![Uploading 微信图片_20231218115732.png…]()

**Comment by zhucan3n** [comment]
![微信图片_20231218115732](https://github.com/ysbing/yadb/assets/118153334/aaf6a041-8cdc-4c49-bf21-73f216305fa2)

**Comment by ysbing** [comment]
> ![微信图片_20231218115732](https://private-user-images.githubusercontent.com/118153334/291146253-aaf6a041-8cdc-4c49-bf21-73f216305fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzM3ODQsIm5iZiI6MTcwMjg3MzQ4NCwicGF0aCI6Ii8xMTgxNTMzMzQvMjkxMTQ2MjUzLWFhZjZhMDQxLThjZGMtNGM0OS1iZjIxLTczZjIxNjMwNWZhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNDI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDBkNzJiMmUwMWY3YWY1ODM5M2IyMzk3MzA5NWYwNDAwNTBjZmVlZmMxZmFjMTI0OWI4YzEwMWMwYjQ3MjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Bcu82wHliBBMzYJfFz8Df4DwpA-dppujQNj9B1nClY)

你好，你可以用另一台手机试一下吗，如果都不行，就可能是你的控制台编码的问题，期待后续反馈

**Comment by zhucan3n** [comment]
我已经用了几部手机测试过才反馈的啦！一部小米两部中兴

**Comment by zhucan3n** [comment]
我把控制台编码改成UTF8但是也没能实现，不知道为什么

**Comment by zhucan3n** [comment]
![image](https://github.com/ysbing/yadb/assets/118153334/edb00912-f95c-4a8b-a55e-062289949bcc)

**Comment by zhucan3n** [comment]
运行windows.bat是下面这个结果
![image](https://github.com/ysbing/yadb/assets/118153334/3a7ae050-76da-4543-b50f-c04b2c601556)

**Comment by zhucan3n** [comment]
你好，我已经解决了。谢谢你，很有用！！！！！！！！！！！！！！

**Comment by ysbing** [comment]
> 你好，我已经解决了。谢谢你，很有用！！！！！！！！！！！！！！

后面是怎么解决的，能分享一下吗
