### ISSUE TITLE
获取布局时如果页面中出现了emoji表情符号会导致xml解析失败

### ISSUE THREAD

**Issue by zhongke-wang** [ysbing/yadb#18]
获取布局时如果页面中出现了emoji表情符号会导致xml解析失败
比如 😃 在布局文件中会显示为 `&#55357;&#56835;`
在python使用以下代码解析时会出现XMLSyntaxError错误

```
from lxml import etree
etree.parse("layout.xml")
```

**Comment by ysbing** [comment]
@zhongke-wang 感谢反馈，已修复
