### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by lzl-hello** [ysbing/yadb#19]
Pls how can I use it on ubuntu

**Comment by lzl-hello** [comment]
![image](https://github.com/ysbing/yadb/assets/96810799/9e90eb2d-0618-49b0-8391-e2dfcad5fc2f)

**Comment by lzl-hello** [comment]
![image](https://github.com/ysbing/yadb/assets/96810799/33fa2ac2-037c-4bd4-8bec-76fcc7965016)

**Comment by zhongke-wang** [comment]
1. 连接设备后将yadb传输到手机

 ```
adb push yadb /data/local/tmp
```

2. 运行以下命令即可在光标处输入“你好，世界”

```
adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard 你好，世界
```

[详细使用](https://github.com/ysbing/yadb/blob/master/readme.md)

**Comment by ysbing** [comment]
@lzl-hello 我使用Linux系统试了一下，是可以的，如果你还是不行的话，你尝试把要输入的字符串用英文双引号括起来
