### ISSUE TITLE
获取布局时>会变成?

### ISSUE THREAD

**Issue by zhucan3n** [ysbing/YADB#21]
比如我这个隐私保护中心 ?>位置服务 会变成 隐私保护中心 ? 位置服务，之前老的版本不会

**Comment by zhucan3n** [comment]
< >都会成为问号，
![image](https://github.com/ysbing/YADB/assets/118153334/c61d55ac-7d3c-4221-ad5c-ecc82f93e6be)
b别的好像不会

**Comment by ysbing** [comment]
可能是优化了emoji表情的问题引起的，我查下

**Comment by ysbing** [comment]
[已修复](https://github.com/ysbing/YADB/commit/c3825c5bfe176c4cbc0c69e916aa5506ec3e21c2)
