### ISSUE TITLE
荣耀安卓14中文输入无反应

### ISSUE THREAD

**Issue by neophack** [ysbing/YADB#27]

**Comment by ysbing** [comment]
贴上运行日志截图，系统关于截图

**Comment by neophack** [comment]
MainException:java.lang.NoSuchMethodError: No interface method getPrimaryClip(Ljava/lang/String;Ljava/lang/String;II)Landroid/content/ClipData; in class Landroid/content/IClipboard; or its super classes (declaration of 'android.content.IClipboard' appears in /system/framework/framework.jar)
	at com.ysbing.yadb.input.ClipboardManager.getPrimaryClip(ClipboardManager.java:29)
	at com.ysbing.yadb.input.ClipboardManager.getText(ClipboardManager.java:51)
	at com.ysbing.yadb.input.Keyboard.getClipboardText(Keyboard.java:62)
	at com.ysbing.yadb.input.Keyboard.setClipboardText(Keyboard.java:49)
	at com.ysbing.yadb.input.Keyboard.run(Keyboard.java:27)
	at com.ysbing.yadb.Main.main(Main.java:27)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:408)

![1007861185](https://github.com/ysbing/YADB/assets/12814250/0c554035-b899-44cb-ac41-a7c7e8b7f8f3)

**Comment by ysbing** [comment]
[yadb.zip](https://github.com/user-attachments/files/16024936/yadb.zip)
把我传上来的yadb.zip，改名yadb，然后你再试试，我打印了一些类信息，把日志再贴上来

**Comment by neophack** [comment]
./adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard 你好，世界
Unable to find method <init> with signature ()V
Aborted

**Comment by ysbing** [comment]
https://github.com/ysbing/YADB/files/15385874/yadb.zip
用这个试试

**Comment by neophack** [comment]
SDK版本:34,开始打印IClipboard对象信息:
方法名称: addPrimaryClipChangedListener
返回类型: void
参数类型: android.content.IOnPrimaryClipChangedListener java.lang.String java.lang.String int int 
----------------------------
方法名称: addPrimaryClipGotListener
返回类型: void
参数类型: android.content.IOnPrimaryClipGotListener java.lang.String java.lang.String int int 
----------------------------
方法名称: areClipboardAccessNotificationsEnabledForUser
返回类型: boolean
参数类型: int 
----------------------------
方法名称: asBinder
返回类型: android.os.IBinder
参数类型: 
----------------------------
方法名称: clearPrimaryClip
返回类型: void
参数类型: java.lang.String java.lang.String int int 
----------------------------
方法名称: getHwInnerService
返回类型: android.os.IBinder
参数类型: 
----------------------------
方法名称: getInterfaceDescriptor
返回类型: java.lang.String
参数类型: 
----------------------------
方法名称: getPrimaryClip
返回类型: android.content.ClipData
参数类型: java.lang.String java.lang.String int int java.lang.String 
----------------------------
方法名称: getPrimaryClipDescription
返回类型: android.content.ClipDescription
参数类型: java.lang.String java.lang.String int int 
----------------------------
方法名称: getPrimaryClipSource
返回类型: java.lang.String
参数类型: java.lang.String java.lang.String int int 
----------------------------
方法名称: hasClipboardText
返回类型: boolean
参数类型: java.lang.String java.lang.String int int 
----------------------------
方法名称: hasPrimaryClip
返回类型: boolean
参数类型: java.lang.String java.lang.String int int 
----------------------------
方法名称: removePrimaryClipChangedListener
返回类型: void
参数类型: android.content.IOnPrimaryClipChangedListener java.lang.String java.lang.String int int 
----------------------------
方法名称: removePrimaryClipGotListener
返回类型: void
参数类型: android.content.IOnPrimaryClipGotListener java.lang.String java.lang.String int int 
----------------------------
方法名称: setClipboardAccessNotificationsEnabledForUser
返回类型: void
参数类型: boolean int 
----------------------------
方法名称: setPrimaryClip
返回类型: void
参数类型: android.content.ClipData java.lang.String java.lang.String int int 
----------------------------
方法名称: setPrimaryClipAsPackage
返回类型: void
参数类型: android.content.ClipData java.lang.String java.lang.String int int java.lang.String 
----------------------------
MainException:java.lang.NoSuchMethodError: No interface method getPrimaryClip(Ljava/lang/String;Ljava/lang/String;II)Landroid/content/ClipData; in class Landroid/content/IClipboard; or its super classes (declaration of 'android.content.IClipboard' appears in /system/framework/framework.jar)
	at com.ysbing.yadb.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:37)
	at com.ysbing.yadb.wrappers.ClipboardManager.getText(ClipboardManager.java:53)
	at com.ysbing.yadb.Device.getClipboardText(Device.java:43)
	at com.ysbing.yadb.Device.setClipboardText(Device.java:56)
	at com.ysbing.yadb.Server.keyboard(Server.java:49)
	at com.ysbing.yadb.Main.main(Main.java:19)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:408)

**Comment by ysbing** [comment]
改好了，去首页拉最新的yadb试试
