### ISSUE TITLE
华为mate20不可用

### ISSUE THREAD

**Issue by wentiancanye** [ysbing/yadb#3]
系统：Android10
型号：华为Mate20Pro

**Comment by ysbing** [comment]
> 系统：Android10
> 型号：华为Mate20Pro

是什么功能不能用，有日志吗，放上来看看

**Comment by wentiancanye** [comment]
所有的不可用哦，是Android系统版本的问题吗
![错误](https://user-images.githubusercontent.com/34967997/103781016-bcdb9b00-5070-11eb-9c70-65c6ed45a041.PNG)

**Comment by ysbing** [comment]
把双引号去掉试试

**Comment by wentiancanye** [comment]
> 把双引号去掉试试

是一样的，也不行哦

**Comment by ysbing** [comment]
使用的yadb是根目录的那个吗？

**Comment by wentiancanye** [comment]
> 使用的yadb是根目录的那个吗？

对的，用的根目录那个，不得行。我正在准备重新编译，加点日志，看看是哪里出错了。

**Comment by ysbing** [comment]
> > 使用的yadb是根目录的那个吗？
> 
> 对的，用的根目录那个，不得行。我正在准备重新编译，加点日志，看看是哪里出错了。

好，辛苦，我这个用根目录的yadb是正常的，你那边找到原因的话贴上来看看哈，谢谢

**Comment by wentiancanye** [comment]
> > > 使用的yadb是根目录的那个吗？
> > 
> > 
> > 对的，用的根目录那个，不得行。我正在准备重新编译，加点日志，看看是哪里出错了。
> 
> 好，辛苦，我这个用根目录的yadb是正常的，你那边找到原因的话贴上来看看哈，谢谢

我重新编译了下，可以用了，但是有个问题：
**使用 `-keyboard 你好，世界` 时文字不会自动输入到编辑框，只存在于剪贴板，不论中英文均不可以。**

之前你编译的无法正常运行的原因可能是 `app` 下面的` build.gradle` 中的 `minSdkVersion` 过小。
原始的为 `minSdkVersion 21`
我调整为 `minSdkVersion 29` 就可以了

**Comment by ysbing** [comment]
> > > > 使用的yadb是根目录的那个吗？
> > > 
> > > 
> > > 对的，用的根目录那个，不得行。我正在准备重新编译，加点日志，看看是哪里出错了。
> > 
> > 
> > 好，辛苦，我这个用根目录的yadb是正常的，你那边找到原因的话贴上来看看哈，谢谢
> 
> 我重新编译了下，可以用了，但是有个问题：
> **使用 `-keyboard 你好，世界` 时文字不会自动输入到编辑框，只存在于剪贴板，不论中英文均不可以。**
> 
> 之前你编译的无法正常运行的原因可能是 `app` 下面的` build.gradle` 中的 `minSdkVersion` 过小。
> 原始的为 `minSdkVersion 21`
> 我调整为 `minSdkVersion 29` 就可以了

不合逻辑，minSdkVersion不影响才对，应该还有其他原因

**Comment by ysbing** [comment]
-keyboard不能输入的问题，你换个别的app编辑框看看，有的app限制粘贴
