### ISSUE TITLE
能加个网页请求不。get post这样的

### ISSUE THREAD

**Issue by enen996** [ysbing/YADB#33]
adb 找不到可以请求的方式

**Comment by ysbing** [comment]
你的具体需求是什么，单纯用命令行做网络请求的话，不是有curl吗

**Comment by enen996** [comment]
就单纯返回响应文本就可以呀。单纯get也可以的呀。大佬。

**Comment by ysbing** [comment]
你先说下为什么不直接用curl

**Comment by ysbing** [comment]
你为什么要用adb里的命令去做网络，直接用电脑的命令不可以吗

**Comment by enen996** [comment]
我手机里插着卡嘛，我想知道当时手机的IP是多少嘛

**Comment by ysbing** [comment]
好，我考虑下怎么加

**Comment by ysbing** [comment]
![image](https://github.com/user-attachments/assets/435b68bc-9309-4d7f-b297-31bfd2bb54e6)

你可以用共享手机网络到电脑，再去用电脑请求，所以我不打算加这个功能
