### ISSUE TITLE
为什么我的中文乱码？

### ISSUE THREAD

**Issue by namexiaolu** [ysbing/yadb#4]
![中文乱码](https://user-images.githubusercontent.com/16086608/105683626-c731dc00-5f2e-11eb-9ae2-624876e86838.jpg)
我的系统是win10系统
这是我的代码：
`adb push yadb /data/local/tmp & adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard '#视频号:namexiaolu  期待回关哦~'`

我先把代码写到txt文件中然后修改后缀为bat，执行后就会乱码。
后来我用vscode直接新建bat文件也是乱码。

**Comment by ysbing** [comment]
你可以参考我放在根目录的bat文件，要先设置编码

**Comment by namexiaolu** [comment]
![image](https://user-images.githubusercontent.com/16086608/105684903-7c18c880-5f30-11eb-889c-ff1a9f2c33a5.png)
根目录的window.bat运行是这样的，

我用vscode改成 LF 
![image](https://user-images.githubusercontent.com/16086608/105686705-84720300-5f32-11eb-896a-5ce1387fa574.png)
但是运行还是乱码，而且运行完之后自动变成了CRLF。

**Comment by ysbing** [comment]
你直接打开cmd，一行一行的输入看看

**Comment by namexiaolu** [comment]
一行一行的输入可以正确显示

**Comment by namexiaolu** [comment]
一行一行的输入可以正确显示

**Comment by ysbing** [comment]
运行根目录的windows.bat出现的错误，感觉是你的命令行工具有问题
