### ISSUE TITLE
请问，这种情况是怎么回事。

### ISSUE THREAD

**Issue by leedsen** [ysbing/yadb#5]
![image](https://user-images.githubusercontent.com/34760768/116357793-7d0f0e00-a82f-11eb-9aed-8185e5de3414.png)

**Comment by leedsen** [comment]
我发现了问题的所在，即使设置了环境变量，还是要手动切换到文件夹所在的目录才有效果，而且不能使用power shell，只能用命令提示符窗口。
如下图
![image](https://user-images.githubusercontent.com/34760768/116361922-19d3aa80-a834-11eb-9043-8f748b05ce4f.png)
可以输入了，奇怪的是，有时候第一遍和第二遍命令并不生效，第三遍才能输入文字。

**Comment by leedsen** [comment]
我删除旧的环境变量重新添加环境变量之后，直接输入命令有效了。
adb push yadb /sdcard/adb
adb shell app_process -Djava.class.path=/sdcard/adb/yadb /sdcard/adb com.ysbing.yadb.Main -keyboard 你好，世界

第一遍不生效是因为输入法有问题，QQ拼音有问题，用百度手机输入法就没问题了。

**Comment by leedsen** [comment]
多谢楼主提供这么好的工具，可以愉快地自动办公了。之前那个adb输入法利用广播途径传递中文，直接输入命令行没有延迟，但是在python中有时候有几十秒的延迟。

**Comment by ysbing** [comment]
> 多谢楼主提供这么好的工具，可以愉快地自动办公了。之前那个adb输入法利用广播途径传递中文，直接输入命令行没有延迟，但是在python中有时候有几十秒的延迟。

好用就好，开源就是要分享给大家用
