### ISSUE TITLE
  可以实现全选然后删除手机文本框文字的功能吗？

### ISSUE THREAD

**Issue by xmexg** [ysbing/yadb#8]

**Comment by ysbing** [comment]
可以实现，你有这种需求的话，我给加上

**Comment by rubyangxg** [comment]
我也想要

**Comment by ysbing** [comment]
adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard "~CLEAR~"

**Comment by ysbing** [comment]
adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard "~CLEAR~"

**Comment by ysbing** [comment]
adb shell app_process -Djava.class.path=/data/local/tmp/yadb /data/local/tmp com.ysbing.yadb.Main -keyboard "\~CLEAR~"
