### ISSUE TITLE
能否跟scrcpy结合实现中文输入

### ISSUE THREAD

**Issue by yilksd** [ysbing/yadb#9]
现在scrcpy有个fork   https://github.com/Genymobile/scrcpy/pull/2904  可以用 --use-adb-keyboard参数然后在设备上安装adbkeyboard来实现中文输入，但是这始终需要单独的输入法，手机上想要用旧有输入法还得切换。yadb可以跟scrcpy结合实现使用电脑上的输入法无缝输入中文吗？

**Comment by ysbing** [comment]
scrcpy实现中文输入的可以监控焦点的变化，如有焦点时，在电脑端唤醒透明编辑框接收电脑输入法的内容，再转发到手机端
